runtime: python27
api_version: 1
threadsafe: yes


handlers:

  - url: /
    static_files: dist/intelligence/index.html
    upload: dist/intelligence/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE