steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/$PROJECT_ID/minerva-angular:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "0.0.0.0    dev.i.rax.io" >> /etc/hosts
        npm rebuild node-sass
        npm run mocksetup
        npm run test:admin-e2e
        npm run test:admin

timeout: 3600s
