steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'ng', '--', 'build', '--prod']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'dist/', 'gs://mnrva-deploy.dev.monplat.rackspace.net']