steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/minerva-testing:latest',
      '.'
      ]

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/$PROJECT_ID/minerva-testing:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        npm rebuild node-sass
        node ./localenv/helpers/createMocks.js
        npm run e2e-ci

timeout: 3600s
images: ['gcr.io/$PROJECT_ID/minerva-testing:latest']
