steps:

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/$PROJECT_ID/minerva-angular:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "0.0.0.0    dev.i.rax.io" >> /etc/hosts
        npm rebuild node-sass
        node ./localenv/helpers/createMocks.js
        npm run test:e2e-ci
        npm run test:unit-ci

timeout: 3600s
images: ['gcr.io/$PROJECT_ID/minerva-testing:latest']
