steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/minerva-testing:latest', '.']

- name: 'gcr.io/$PROJECT_ID/minerva-testing:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        cd /app
        Xvfb :10 -screen 0 1920x1080x24 2>&1 >/dev/null
        sleep 20
        npm run e2e

- name: 'gcr.io/$PROJECT_ID/minerva-testing:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        cd /app
        Xvfb :10 -screen 0 1920x1080x24 2>&1 >/dev/null
        sleep 20
        npm run test-headless

images: ['gcr.io/$PROJECT_ID/minerva-testing:latest']
