steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'ng', '--', 'build', '--prod']

- name: 'gcr.io/cloud-builders/docker'
  id: DEPLOY
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/minerva:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/minerva:latest',
    '-f', 'Dockerfile-test',
    '.'
    ]

images: ['gcr.io/$PROJECT_ID/minerva-testing:latest','gcr.io/$PROJECT_ID/minerva-testing:$SHORT_SHA']