steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build-deploy', '--prod']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-d', '-r', 'dist/intelligence/', 'gs://mnrva-deploy.dev.monplat.rackspace.net/intelligence']